# Phase 8 Vivado synthesis script for the optimized sequential architecture.
# This flow intentionally stops after synthesis. It does not run opt/place/route.
# Default top is the flattened synthesis wrapper because Vivado board-level
# synthesis can be fragile with unpacked array top-level ports.

set script_dir [file dirname [file normalize [info script]]]
set repo_root [file normalize [file join $script_dir ".."]]
set output_dir [file join $repo_root "results" "phase8_synthesis_seq"]
set build_dir [file join $repo_root "build" "vivado_seq"]

file mkdir $output_dir
file mkdir $build_dir

set default_part_name xc7a35tcpg236-1
set clock_period_ns 10.000
set run_ooc 1

source [file join $script_dir "filelist_rtl_seq.tcl"]

if {![info exists default_synth_top] || ($default_synth_top eq "")} {
    error "default_synth_top is not defined by syn_seq/filelist_rtl_seq.tcl"
}

if {![info exists argv]} {
    set argv [list]
}
set script_args $argv
set script_argc [llength $script_args]

set top_name $default_synth_top
set part_name $default_part_name
set positional_count 0

for {set arg_idx 0} {$arg_idx < $script_argc} {incr arg_idx} {
    set arg [lindex $script_args $arg_idx]

    if {$arg eq "-top"} {
        incr arg_idx
        if {$arg_idx >= $script_argc} {
            error "Missing value after -top"
        }
        set top_name [lindex $script_args $arg_idx]
    } elseif {$arg eq "-part"} {
        incr arg_idx
        if {$arg_idx >= $script_argc} {
            error "Missing value after -part"
        }
        set part_name [lindex $script_args $arg_idx]
    } elseif {$arg eq "-clock_period"} {
        incr arg_idx
        if {$arg_idx >= $script_argc} {
            error "Missing value after -clock_period"
        }
        set clock_period_ns [lindex $script_args $arg_idx]
    } elseif {$arg eq "-no_ooc"} {
        set run_ooc 0
    } elseif {$positional_count == 0} {
        set top_name $arg
        incr positional_count
    } elseif {$positional_count == 1} {
        set part_name $arg
        incr positional_count
    } else {
        error "Unknown extra argument: $arg"
    }
}

puts "Phase 8 sequential Vivado synthesis"
puts "Repository root: $repo_root"
puts "Output directory: $output_dir"
puts "Top module: $top_name"
puts "FPGA part: $part_name"
puts "Clock: clk, $clock_period_ns ns"
puts "Out-of-context synthesis: $run_ooc"

create_project -force adaptive_gs_mimo_detector_seq $build_dir -part $part_name
set_property target_language Verilog [current_project]

set include_dirs [list \
    [file join $repo_root "rtl"] \
    [file join $repo_root "rtl_seq"] \
]

puts "SystemVerilog include directories:"
foreach include_dir $include_dirs {
    set include_dir_norm [file normalize $include_dir]
    if {![file isdirectory $include_dir_norm]} {
        error "Missing include directory: $include_dir_norm"
    }
    puts "  $include_dir_norm"
}

# Vivado 2025.2 does not support read_verilog -include_dirs. Set include
# directories on the active source fileset before reading RTL files.
set_property include_dirs $include_dirs [current_fileset]

puts "Reading sequential RTL files:"
foreach rtl_file $rtl_seq_files {
    set rtl_path [file normalize [file join $repo_root $rtl_file]]
    if {![file exists $rtl_path]} {
        error "Missing RTL file from syn_seq/filelist_rtl_seq.tcl: $rtl_path"
    }

    puts "  read_verilog -sv $rtl_path"
    set read_status [catch {
        read_verilog -sv $rtl_path
    } read_msg]

    if {$read_status != 0} {
        puts "Failed while reading RTL file: $rtl_path"
        error $read_msg
    }
}

# Generated in the results directory so synthesis is constrained without adding
# another source-controlled file. The script remains synthesis-only.
set clock_xdc [file join $output_dir "clock_seq.xdc"]
set clock_fh [open $clock_xdc w]
puts $clock_fh [format {create_clock -period %.3f -name clk [get_ports clk]} $clock_period_ns]
close $clock_fh
read_xdc $clock_xdc

set_property top $top_name [current_fileset]
update_compile_order -fileset sources_1

set synth_args [list -top $top_name -part $part_name]
if {$run_ooc} {
    lappend synth_args -mode out_of_context
}

synth_design {*}$synth_args

if {[llength [get_clocks -quiet clk]] == 0} {
    create_clock -period $clock_period_ns -name clk [get_ports clk]
}

report_utilization -file [file join $output_dir "utilization_seq.rpt"]
report_timing_summary -file [file join $output_dir "timing_seq.rpt"]

set power_status [catch {
    report_power -file [file join $output_dir "power_seq.rpt"]
} power_msg]

if {$power_status != 0} {
    puts "Power report was not generated by Vivado:"
    puts $power_msg
}

write_checkpoint -force [file join $output_dir "synth_seq.dcp"]

puts "Sequential synthesis reports written to: $output_dir"
